Release 5.0.0
voxpupuli/rspec-puppet-facts pull request #188
Opened 2024-06-21 08:06 UTC by bastelfreak

2024-06-21 08:17 UTC, bastelfreak commented
I would like to include https://github.com/voxpupuli/rspec-puppet-facts/pull/189 as well

2024-06-27 15:05 UTC, ekohl requested changes
This suggestion assumes https://github.com/voxpupuli/rspec-puppet-facts/pull/189 is merged, but I'm a bit hesitant on that. I'd prefer to formally deprecate it first.

That means:
* Make sure the configuration option to switch is well documented
* Migration guide
* Announce the next major version will drop it
* Communicate this (also to PDK users)

2024-06-27 15:05 UTC, ekohl commented on CHANGELOG.md
> +for a long long time, the first level of keys in a factsets were symbols. Following nested hashes always had strings. This doesn't make sense and looks confusing. Also the original data contains only
```suggestion
For a long long time, the first level of keys in a factsets were symbols. This was fine before there were structured facts, but structured facts ended up as nested hashes that always had strings. This doesn't make sense and easy to get wrong. The original data contains only strings so conversion actually cost performance.

We now flip the default to increase performance, make code more readable and remove some footguns. This major release also switched to FacterDB 3, which doesn't contain [legacy facts](https://www.puppet.com/docs/puppet/7/core_facts.html) nor factset for EoL operating systems or EoL facter versions.
```

2024-06-28 16:55 UTC, bastelfreak commented
* I raised https://github.com/voxpupuli/rspec-puppet-facts/pull/193 which updates the README.md and deprecates symbolized facts
* I updated the release notes for 3.0.0 (https://github.com/voxpupuli/rspec-puppet-facts/issues/170), say mentioned that symbolized keys are deprecated with the 5.0.0 release
* I moved https://github.com/voxpupuli/rspec-puppet-facts/issues/190 to the release summary for 6.0.0

2024-07-08 08:41 UTC, rwaffen approved these changes

2024-07-08 08:44 UTC, merged